### ISSUE TITLE
Feature Request: Detect whether or not to use TouchableHighlight or TouchableNativeFeedback

### ISSUE THREAD

**Issue by Andrewpk** [APSL/react-native-button#13]
It would be cool if this had functionality to automatically detect whether or not it should use TouchableHighlight or add TouchableNativeFeedback support.

**Comment by alvaromb** [comment]
Sure @Andrewpk!

If everything goes OK, expect a release tomorrow :)

**Comment by Andrewpk** [comment]
@alvaromb thanks! that's awesome.

**Comment by alvaromb** [comment]
Hi @Andrewpk!

Let me know if this works for you https://github.com/APSL/react-native-button/commit/6a516d0b12fdf2d19bb64db02f18ffe088498e46.

Sorry for the delay, I had to take the kid to the hospital.

**Comment by alvaromb** [comment]
This has landed into ``v2.4.0`` https://github.com/APSL/react-native-button/pull/16

**Comment by Andrewpk** [comment]
Thank you for your work on this! Normally I'm not so absentee - making a request and then disappearing. If I have any future requests I promise to at least propose a solution/PR.

**Comment by alvaromb** [comment]
Cool to have helped @Andrewpk!

I'm usually very slow on maintaining this repos because we have a lot of work and we've just started to grow our mobile team. Expect more frequent updates soon!
