### ISSUE TITLE
Can we lossen up props.children check?

### ISSUE THREAD

**Issue by gorangajic** [APSL/react-native-button#14]
Currently it will show warning if you provided anything else than text. But in react-native it's [possible](https://facebook.github.io/react-native/docs/text.html#nested-text) to nest text one into another.

My use case is to show [icon](https://github.com/oblador/react-native-vector-icons) next to text 

```javascript
<Button>
    <Icon name="sign-in"/><Text> Sign up </Text>
</Button>
```

**Comment by alvaromb** [comment]
Hi @gorangajic and thanks for your feedback?

Do you want to nest text only or you need to nest any other node inside (to display an icon, for example)?

Please let me know what works best for you and I'll publish a release tomorrow.

**Comment by alvaromb** [comment]
Hi @gorangajic!

I'll be more than happy to provide a solution for you :)

Do you want to nest only ``Text`` or any view?

**Comment by gorangajic** [comment]
Yup I think that `Text` will work fine.

Thank you

**Comment by alvaromb** [comment]
Closing in favour of #23.
