### ISSUE TITLE
ES6 doesn't work on react-native

### ISSUE THREAD

**Issue by holyxiaoxin** [APSL/react-native-button#2]
I was wondering how did you get 

`import Button from 'apsl-react-native-button';` to work. I could only use es5 syntax of importing modules.

**Comment by alvaromb** [comment]
Hello @holyxiaoxin! what's your Babel config?

**Comment by alvaromb** [comment]
Try to use a ``.babelrc`` config: 

```json
{
  "whitelist": [
    "es6.modules"
  ]
}
```

Source: http://wiredify.com/shohey1226/logs/React-Native-with-bebelrc

**Comment by alvaromb** [comment]
I'm closing the issue, let me know if you need something @holyxiaoxin :)
