### ISSUE TITLE
New npm release

### ISSUE THREAD

**Issue by danielweinmann** [APSL/react-native-button#20]
Hey @alvaromb, can you release latest code to npm?

Thanks a lot!

**Comment by alvaromb** [comment]
Hello @danielweinmann!!

It's already released :)

<img width="397" alt="rls" src="https://cloud.githubusercontent.com/assets/289640/13465013/097001e2-e094-11e5-94e1-0b3ba0f5c4a8.png">

**Comment by danielweinmann** [comment]
Oh, sorry!

I looked for a "bump version" commit or something like that and didn't care to actually look for it. My bad.

**Comment by alvaromb** [comment]
No problem @danielweinmann !! :wink:

**Comment by codeheroics** [comment]
@alvaromb Hi, I'm using this instead of using a new issue, could you tag a new version and release it on npm? The last version, v2.5.0, is 13 commits behind master, and includes corrected bugs, like https://github.com/APSL/react-native-button/pull/32 .

**Comment by alvaromb** [comment]
Yes! Will do that tomorrow, sorry I'm out on holidays. 

Enviado desde mi iPhone
