### ISSUE TITLE
Wrapping all children in <Text>

### ISSUE THREAD

**Issue by Andrewpk** [APSL/react-native-button#23]
Most mobile sdk's allow for buttons to contain nearly anything that is a "View" or whatever the base UI component on that system is. With this plugin, a decision was made to wrap everything in a `<Text>` element. What are your thoughts on loosening that up so that we can nest other renderable elements and have them rendered as react-native sees fit instead of wrapping them in `<Text>`?

Thanks for this plugin and all your work!

**Comment by alvaromb** [comment]
I should support more than just a text, it's true. I'll try to merge this week something that looses the text restriction.
