### ISSUE TITLE
Add "activeOpacity" attribute

### ISSUE THREAD

**Issue by matteomunaretto** [APSL/react-native-button#31]
As requested on the following https://github.com/APSL/react-native-button/pull/25, is it possible to add the attribute? On Android if you press rapidly you don't have any feedback.

Thanks, 
Matteo

**Comment by alvaromb** [comment]
Under Android the library won't render `TouchableOpacity` but `TouchableNativeFeedback` instead. Anyway, the merge is planned so I'll do that ASAP.
