### ISSUE TITLE
Android - Circular indeterminate `ProgressBarAndroid`is deprecated. Use `ActivityIndicator` instead on RN 0.28. 

### ISSUE THREAD

**Issue by ganapativs** [APSL/react-native-button#34]
Please support the latest version of RN. Thanks.

**Comment by yasaricli** [comment]
@ganapativs +1

**Comment by alvaromb** [comment]
Hey! I'm currently on family vacation, I will update the component the next week. Thanks for being patient. Family matters.

**Comment by alvaromb** [comment]
Closed by https://github.com/APSL/react-native-button/releases/tag/v3.0.0
