### ISSUE TITLE
Invalid prop children of type object supplied to Button, expected string

### ISSUE THREAD

**Issue by calclavia** [APSL/react-native-button#40]
I have the following code using (https://github.com/oblador/react-native-vector-icons).
I'm not sure why I'm getting this warning. My button renders fine with the icon.

```
                <Button style={styles.platformButton}>
                    <Icon 
                        name={this.props.id} 
                        size={buttonSize - 20}
                        color= '#ffffff'
                    />
                </Button>
```

**Comment by alvaromb** [comment]
Which version of the button are you running, @calclavia ?

**Comment by calclavia** [comment]
I installed this just yesterday, so I'm guessing it's the latest v2.5.0

**Comment by alvaromb** [comment]
Ok, views inside the button are not yet supported, but expect a 3.0 release today! ☺️
