### ISSUE TITLE
Support for testing

### ISSUE THREAD

**Issue by bartonhammond** [APSL/react-native-button#46]
The following changes run fine w/ Jest:

```
...
   textStyle: PropTypes.string,
    disabledStyle: PropTypes.string,
...
   background: PropTypes.any
```

But the original does not:

```
 FAIL  src/components/__tests__/FormButton-test.js
Runtime Error
  - TypeError: Cannot read property 'style' of undefined
        at Object.<anonymous> (node_modules/apsl-react-native-button/Button.js:22:25)
        at Runtime._execModule (node_modules/jest-cli/src/Runtime/Runtime.js:261:17)
        at Object.<anonymous> (src/components/FormButton.js:22:12)
        at Object.<anonymous> (src/components/__tests__/FormButton-test.js:27:16)
        at jasmine2 (node_modules/jest-jasmine2/src/index.js:252:16)
        at process._tickCallback (internal/process/next_tick.js:103:7)
1 test suite failed, 0 tests passed (0 total in 1 test suite, run time 6.012s)
```

I think we've had this discussion before - see pull request #12 -  I don't know how to support older Forks in my Repo and update to the newest?  I've got this for backward compatibility: [https://github.com/bartonhammond/react-native-button](https://github.com/bartonhammond/react-native-button).  

Is there a way to get this addressed so I don't have to fork it just for testing?

**Comment by bartonhammond** [comment]
Please see comments here: [https://github.com/facebook/jest/issues/651](https://github.com/facebook/jest/issues/651)

**Comment by alvaromb** [comment]
The thing is that the code in the props is completely right, this is more a Jest or Jest config issue, not about this component. I'm jumping again into the Jest issue, let's see if we can finally fix this.

**Comment by bartonhammond** [comment]
I got a reference to try from the Jest team.  I will try later today and
report back.

**Comment by alvaromb** [comment]
The component is tested with snapshot tests and it's working great so far, do you still have any trouble testing @bartonhammond ?

**Comment by bartonhammond** [comment]
No problem - thanks!

**Comment by alvaromb** [comment]
Great!

Please let me know if something else pops up!
