### ISSUE TITLE
Align problem on RN 0.37.0

### ISSUE THREAD

**Issue by marcosinigaglia** [APSL/react-native-button#54]
The button text on Android is align on the top left, i think the cause is the Text element that wrap the other Text children.

**Comment by scriptfans** [comment]
Android has this problem.

**Comment by alvaromb** [comment]
Thanks for reporting!

Can you attach me an screenshot?

Will try to solve this ASAP :)

**Comment by scriptfans** [comment]
![fd8f3f00-33dc-4124-ae74-c97a9f701660](https://cloud.githubusercontent.com/assets/359790/20171394/6798eaba-a76b-11e6-86d2-28a70a246fbf.png)

**Comment by scriptfans** [comment]
@alvaromb

**Comment by alvaromb** [comment]
Solved in https://github.com/APSL/react-native-button/releases/tag/v3.0.2

Thanks.
