### ISSUE TITLE
Support Babel 6

### ISSUE THREAD

**Issue by cava23** [APSL/react-native-button#8]
React Native 0.16.0-rc uses Babel 6 so this would be nice. I'm not sure how much work that is to do.

**Comment by alvaromb** [comment]
Hi @cava23!!

Let me know if this PR https://github.com/APSL/react-native-button/pull/9 works for you and I'll merge it and make a release.

**Comment by alvaromb** [comment]
I think it's the best solution right now (take a look at this issue https://github.com/rackt/redux/issues/1033), but keep in mind that the component is written un ES6 style so you should configure your own ``.babelrc`` in order to make it working.

**Comment by cava23** [comment]
Thanks for the PR. Unfortunately, I’m still having trouble. react-native-button pulls in it’s own version of react-native since I guess 0.16.0-rc doesn’t satisfy the dependency. I’m wondering if that’s an npm bug. I’m just going back to 0.15.0 for now. Uhhggg.

**Comment by cava23** [comment]
Changing the last line of Button.js to:
module.exports = Button;
got it working on 0.16.0-rc.

**Comment by alvaromb** [comment]
That's strange. I'm going to change the ES6 style and make a release. Once it's done, let me know if it works for you.

**Comment by alvaromb** [comment]
@cava23 keep in mind that the PR hasn't been merged yet, so if you want to try it you should install from it's own branch.

**Comment by alvaromb** [comment]
Just pushed https://github.com/APSL/react-native-button/releases/tag/v2.3.0. Let me know if it works for you!

**Comment by cava23** [comment]
That worked! Thanks.

**Comment by cava23** [comment]
btw, this commit https://github.com/facebook/react-native/commit/dff8f53664009f49756c79f5f7c4982eaa39a5c3 <https://github.com/facebook/react-native/commit/dff8f53664009f49756c79f5f7c4982eaa39a5c3> fixes the issue with ES6 module export.
